# Home Page Expected Data
ABOUT_US = "We come from hundreds of ethnic and language backgrounds, yet we are united by common goals. Above all, we want to honor Jehovah, the God of the Bible and the Creator of all things. We do our best to imitate Jesus Christ and are proud to be called Christians. Each of us regularly spends time helping people learn about the Bible and God’s Kingdom. Because we witness, or talk, about Jehovah God and his Kingdom, we are known as Jehovah’s Witnesses."

FOOTER_TEXTS = ['Bible Teachings', 'Bible Questions Answered', 'Bible Verses Explained', 'Bible Study Course',
                'Bible Study Tools', 'Peace & Happiness', 'Marriage & Family', 'Teens & Young Adults', 'Children',
                'Faith in God', 'Science & the Bible', 'History & the Bible', 'Library', 'Bibles', 'Magazines',
                'Books & Brochures', 'Article Series', 'Meeting Workbooks', 'Guidelines', 'JW Broadcasting®', 'Videos',
                'Music', 'Audio Dramas', 'Dramatic Bible Readings', 'News', 'About Us', 'Frequently Asked Questions',
                'Request a Visit', 'Contact Us', 'Bethel Tours', 'Meetings', 'Memorial', 'Conventions', 'Activities',
                'Experiences', 'Around the World']
FOOTER_LINKS = ['https://www.jw.org/en/bible-teachings/', 'https://www.jw.org/en/bible-teachings/questions/',
                'https://www.jw.org/en/bible-teachings/bible-verses/',
                'https://www.jw.org/en/bible-teachings/guided-bible-study-course/',
                'https://www.jw.org/en/bible-teachings/bible-study-tools/',
                'https://www.jw.org/en/bible-teachings/peace-happiness/',
                'https://www.jw.org/en/bible-teachings/family/', 'https://www.jw.org/en/bible-teachings/teenagers/',
                'https://www.jw.org/en/bible-teachings/children/',
                'https://www.jw.org/en/bible-teachings/faith-in-god/', 'https://www.jw.org/en/bible-teachings/science/',
                'https://www.jw.org/en/bible-teachings/history/', 'https://www.jw.org/en/library/',
                'https://www.jw.org/en/library/bible/', 'https://www.jw.org/en/library/magazines/',
                'https://www.jw.org/en/library/books/', 'https://www.jw.org/en/library/series/',
                'https://www.jw.org/en/library/jw-meeting-workbook/', 'https://www.jw.org/en/library/guidelines/',
                'https://www.jw.org/en/library/videos/#en/categories/VODStudio',
                'https://www.jw.org/en/library/videos/', 'https://www.jw.org/en/library/music-songs/',
                'https://www.jw.org/en/library/audio-bible-dramas/',
                'https://www.jw.org/en/library/dramatic-bible-readings/', 'https://www.jw.org/en/news/',
                'https://www.jw.org/en/jehovahs-witnesses/', 'https://www.jw.org/en/jehovahs-witnesses/faq/',
                'https://www.jw.org/en/jehovahs-witnesses/request-a-visit/',
                'https://www.jw.org/en/jehovahs-witnesses/contact/',
                'https://www.jw.org/en/jehovahs-witnesses/bethel-tours/',
                'https://www.jw.org/en/jehovahs-witnesses/meetings/',
                'https://www.jw.org/en/jehovahs-witnesses/memorial/',
                'https://www.jw.org/en/jehovahs-witnesses/conventions/',
                'https://www.jw.org/en/jehovahs-witnesses/activities/',
                'https://www.jw.org/en/jehovahs-witnesses/experiences/',
                'https://www.jw.org/en/jehovahs-witnesses/worldwide/']

footer_test_cases = list(zip(FOOTER_TEXTS, FOOTER_LINKS))

# Article Page Expected Data

SCIENCE_SERIES = [('Viewpoints on the Origin of Life', 0),
                  ('Was It Designed?', 1),
                  ('Evolution Versus Creation', 2),
                  ('The Bible’s Scientific Accuracy', 3)]

BIBLE_SERIES = [('God', 0),
                ('The Bible', 1),
                ('Jesus', 2),
                ('God’s Kingdom', 3),
                ('Spirit Realm', 4),
                ('Life and Death', 5),
                ('Suffering', 6),
                ('Faith and Worship', 7),
                ('Holidays and Celebrations', 8),
                ('Lifestyle and Morals', 9)]

HAPPINESS_SERIES = [('Coping With Tragedy', 0),
                    ('Physical and Mental Health', 1),
                    ('Employment and Money', 2),
                    ('Relationships', 3),
                    ('Habits and Addictions', 4)]

FAMILY_SERIES = [('Dating and Courtship', 0),
                 ('Marriage', 1),
                 ('Relatives', 2),
                 ('Managing Money', 3),
                 ('Communication', 4),
                 ('Raising Children', 5),
                 ('Raising Teenagers', 6)]

TEEN_SERIES = [('Friends', 0),
               ('Family', 1),
               ('Technology', 2),
               ('School', 3),
               ('Life Skills', 4),
               ('Identity', 5),
               ('Bad Habits', 6),
               ('Free Time', 7),
               ('Sex', 8),
               ('Dating', 9),
               ('Physical Health', 10),
               ('Emotional Health', 11),
               ('Spirituality', 12)]

FAITH_SERIES = [('Building Faith in God', 0),
                ('Prayer', 1),
                ('Bible Reading and Study', 2),
                ('Developing Godly Qualities', 3),
                ('Imitate Their Faith​—Bible Characters Brought to Life', 4)]

HISTORY_SERIES = [('History of the Bible', 0),
                  ('Bible Manuscripts', 1),
                  ('Bible Translations', 2),
                  ('Bible Translators', 3),
                  ('The Bible’s Historical Accuracy', 4)]

SCIENCE_PUBLICATIONS = [("Was Life Created?", "https://www.jw.org/en/library/books/was-life-created/"),
                        ("The Origin of Life​—Five Questions Worth Asking",
                         "https://www.jw.org/en/library/books/origin-of-life-5-questions/")]

# Video Page Expected Data
SECTION_NAMES = ['JW Broadcasting', 'Children', 'Teenagers', 'Family', 'Programs and Events', 'Our Activities',
                 'Our Meetings and Ministry', 'Our Organization', 'The Bible', 'Dramas', 'Series', 'Music',
                 'Interviews and Experiences', 'Audio Descriptions']

SECTION_TARGETS = ["https://www.jw.org/en/library/videos/#en/categories/VODStudio",
                   "https://www.jw.org/en/library/videos/#en/categories/VODChildren",
                   "https://www.jw.org/en/library/videos/#en/categories/VODTeenagers",
                   "https://www.jw.org/en/library/videos/#en/categories/VODFamily",
                   "https://www.jw.org/en/library/videos/#en/categories/VODProgramsEvents",
                   "https://www.jw.org/en/library/videos/#en/categories/VODOurActivities",
                   "https://www.jw.org/en/library/videos/#en/categories/VODMinistry",
                   "https://www.jw.org/en/library/videos/#en/categories/VODOurOrganization",
                   "https://www.jw.org/en/library/videos/#en/categories/VODBible",
                   "https://www.jw.org/en/library/videos/#en/categories/VODMovies",
                   "https://www.jw.org/en/library/videos/#en/categories/VODSeries",
                   "https://www.jw.org/en/library/videos/#en/categories/VODMusicVideos",
                   "https://www.jw.org/en/library/videos/#en/categories/VODIntExp",
                   "https://www.jw.org/en/library/videos/#en/categories/VODAudioDescriptions"]

section_test_cases = list(zip(SECTION_NAMES, SECTION_TARGETS))

AVAILABLE_LANGUAGES = [("CONTROL TEST OF FICTIONAL LANGUAGE", False),
                       ("OTHER LANGUAGES ARE CORRECT AND DO PRESENT ON SITE", False), ('Abaknon', True),
                       ('Abbey', True), ('Abkhaz', True), ('Abua', True), ('Abui', True),
                       ('Acadian', True), ('Achi', True), ('Achi (Cubulco)', True), ('Achi (Rabinal)', True),
                       ('Acholi', True), ('Achuar-Shiwiar', True), ('Adhola', True), ('Adyghe', True),
                       ('Afrikaans', True), ('Ahanta', True), ('Aja', True), ('Ajië', True), ('Akateko', True),
                       ('Akha', True), ('Albanian', True), ('Albanian (Gheg)', True), ('Albanian Sign Language', True),
                       ('Algonquin', True), ('Alsatian', True), ('Altai', True), ('Alur', True), ('Ambae (East)', True),
                       ('American Sign Language', True), ('Amharic', True), ('Amis', True), ('Amuzgo (Guerrero)', True),
                       ('Anal', True), ('Angolan Sign Language', True), ('Anyin (Indenie)', True), ('Apma', True),
                       ('Arabic', True), ('Arabic (Algeria)', True), ('Arabic (Egypt)', True), ('Arabic (Iraq)', True),
                       ('Arabic (Jordan)', True), ('Arabic (Lebanon)', True), ('Arabic (Morocco)', True),
                       ('Arabic (Sudanese Creole)', True), ('Arabic (Sudanese)', True), ('Arabic (Syria)', True),
                       ('Arabic (Tunisia)', True), ('Argentinean Sign Language', True), ('Arhuaco', True),
                       ('Armenian', True), ('Armenian (Eastern dialect)', True), ('Armenian (West)', True),
                       ('Armenian Sign Language', True), ('Ashaninka', True), ('Assamese', True), ('Assyrian', True),
                       ('Assyro-Chaldean (Silopi)', True), ('Atayal', True), ('Ateso', True), ('Attié', True),
                       ('Aukan', True), ('Australian Sign Language', True), ('Austrian Sign Language', True),
                       ('Avar', True), ('Awa (Cuaiquer)', True), ('Awadhi', True), ('Awajun', True), ('Awing', True),
                       ('Aymara', True), ('Azerbaijani', True), ('Azerbaijani (Arabic)', True),
                       ('Azerbaijani (Cyrillic)', True), ('Ba', True), ('Bacama', True), ('Badaga', True),
                       ('Bafia', True), ('Bakoko', True), ('Balinese', True), ('Bambara', True), ('Bamun', True),
                       ('Banda (Mid-Southern)', True), ('Baniwa', True), ('Banjar', True), ('Baoule', True),
                       ('Bari', True), ('Bariba', True), ('Barwe', True), ('Bashkir', True), ('Basque', True),
                       ('Bassa (Cameroon)', True), ('Bassa (Liberia)', True), ('Batak (Dairi)', True),
                       ('Batak (Karo)', True), ('Batak (Simalungun)', True), ('Batak (Toba)', True), ('Beas', True),
                       ('Belgian French Sign Language', True), ('Belize Kriol', True), ('Belorussian', True),
                       ('Bembe', True), ('Bengali', True), ('Berom', True), ('Bété', True),
                       ('Betsimisaraka (Northern)', True), ('Betsimisaraka (Southern)', True), ('Bhojpuri', True),
                       ('Bhojpuri (Mauritius)', True), ('Biak', True), ('Bicol', True), ('Bidayuh (Bukar)', True),
                       ('Bisa (Lebir)', True), ('Bislama', True), ('Bissau Guinean Creole', True),
                       ('Blaan (Sarangani)', True), ('Blackfoot', True), ('Bolivian Sign Language', True),
                       ('Bomu', True), ('Bosnian', True), ('Botswana Sign Language', True), ('Boulou', True),
                       ('Brazilian Sign Language', True), ('Bribri', True), ('British Sign Language', True),
                       ('Budza', True), ('Bulgarian', True), ('Bulgarian Sign Language', True), ('Bunun (South)', True),
                       ('Bura', True), ('Burundi Sign Language', True), ('Buryat', True), ('Bushi', True),
                       ('Bushilele', True), ('Bushoong', True), ('Cabécar (Tayní)', True),
                       ('Cakchiquel (Central)', True), ('Cakchiquel (Eastern)', True), ('Cakchiquel (Western)', True),
                       ('Cambodian', True), ('Cambodian Sign Language', True), ('Carib', True), ('Catalan', True),
                       ('Cebuano', True), ('Central African Republic Sign Language', True),
                       ('Central Alaskan Yupik', True), ('Cha’palaa', True), ('Chamorro', True),
                       ('Changana (Mozambique)', True), ('Changana (Zimbabwe)', True), ('Chavacano', True),
                       ('Chechen', True), ('Chedungun (Coast)', True), ('Cherokee', True),
                       ('Chhattisgarhi (Devanagari)', True), ('Chichewa', True), ('Chiga', True),
                       ('Chilean Sign Language', True), ('Chin (Falam)', True), ('Chin (Hakha)', True),
                       ('Chin (Kuki)', True), ('Chin (Mara)', True), ('Chin (Tiddim)', True), ('Chin (Zotung)', True),
                       ('Chinantec (Ojitlan)', True), ('Chinese (Fuzhounese)', True), ('Chinese (Shanghainese)', True),
                       ('Chinese (Sichuanese)', True), ('Chinese (Wenzhounese)', True), ('Chinese (Yunnanese)', True),
                       ('Chinese Cantonese (Simplified)', True), ('Chinese Cantonese (Traditional)', True),
                       ('Chinese Mandarin (Simplified)', True), ('Chinese Mandarin (Traditional)', True),
                       ('Chinese Sign Language', True), ('Chiquitano', True), ('Chitonga', True),
                       ('Chitonga (Malawi)', True), ('Chitonga (Zimbabwe)', True), ('Chitumbuka', True),
                       ('Chiyao', True), ('Choctaw', True), ('Chokwe', True), ('Chol', True),
                       ('Chontal (Oaxaca)', True), ('Chontal (Tabasco)', True), ('Chopi', True),
                       ("Chorote (Iyojwa'ja)", True), ('Chuabo', True), ('Chuj', True), ('Chuukese', True),
                       ('Chuvash', True), ('Cibemba', True), ('Cinamwanga', True), ('Cinyanja', True),
                       ('Colombian Sign Language', True), ('Como Karim', True), ('Comorian (Ngazidja)', True),
                       ('Congolese Sign Language', True), ('Cora (El Nayar)', True), ('Corsican', True),
                       ('Costa Rican Sign Language', True), ('Cree Plains (Roman)', True),
                       ('Cree Plains (Syllabics)', True), ('Cree Southern East (Roman)', True),
                       ('Cree West Swampy (Roman)', True), ('Cree West Swampy (Syllabics)', True),
                       ('Crimean Tatar', True), ('Crimean Tatar (Cyrillic)', True), ('Croatian', True),
                       ('Croatian Sign Language', True), ('Cuban Sign Language', True), ('Cubeo', True),
                       ('Curripaco', True), ('Czech', True), ('Czech Sign Language', True), ('Dagaare', True),
                       ('Dagbani', True), ('Dakota', True), ('Damara', True), ('Dangme', True), ('Danish', True),
                       ('Danish Sign Language', True), ('Dargwa', True), ('Dari', True), ('Dayak Ahe', True),
                       ('Dayak Ngaju', True), ('Dayak Siang', True), ('Dayak Tomun', True), ('Dendi', True),
                       ('Dengese', True), ('Dida (Lakota)', True), ('Digor', True), ('Dinka', True), ('Diola', True),
                       ('Ditammari', True), ('Dogon (Toro So)', True), ('Douala', True), ('Drehu', True),
                       ('Dungan', True), ('Dusun', True), ('Dutch', True), ('Dutch (Belgium)', True),
                       ('Dutch (Suriname)', True), ('Dutch Sign Language', True), ('Dzongkha (Roman)', True),
                       ('Dzongkha (Tibetan)', True), ('Ebira', True), ('Ecuadorian Sign Language', True), ('Edo', True),
                       ('Efate (North)', True), ('Efate (South)', True), ('Efik', True), ('Emberá (Catío)', True),
                       ('Emberá (Chamí)', True), ('Emberá (Northern)', True), ('English', True),
                       ('English (Nigeria)', True), ('Erzya', True), ('Esan', True), ('Estonian', True),
                       ('Estonian Sign Language', True), ('Ethiopian Sign Language', True), ('Eton', True),
                       ('Ewe', True), ('Ewondo', True), ('Fang', True), ('Fante', True), ('Faroese', True),
                       ('Fataluku', True), ("Fe'fe'", True), ('Fiji Sign Language', True), ('Fijian', True),
                       ('Filipino Sign Language', True), ('Finnish', True), ('Finnish Sign Language', True),
                       ('Flemish Sign Language', True), ('Fon', True), ('Frafra', True), ('French', True),
                       ('French (Benin)', True), ('French (Canada)', True), ('French Sign Language', True),
                       ('Frisian', True), ('Fulfulde (Cameroon)', True), ('Fulfulde (Nigerian)', True),
                       ('Futuna (East)', True), ('Fwâi', True), ('Ga', True), ('Gagauz', True),
                       ('Gagauz (Roman)', True), ('Galician', True), ('Garhwali', True), ('Garifuna', True),
                       ('Garo (Abeng)', True), ('Gbaya', True), ('Gedeo', True), ('Georgian', True),
                       ('Georgian Sign Language', True), ('German', True), ('German Sign Language', True),
                       ('Ghanaian Sign Language', True), ('Ghomálá’', True), ('Giryama', True), ('Gitonga', True),
                       ('Gokana', True), ('Gourmanchéma', True), ('Gouro', True), ('Grebo', True), ('Greek', True),
                       ('Greek Sign Language', True), ('Greenlandic', True), ('Greenlandic (East)', True),
                       ('Guadeloupean Creole', True), ('Guahibo', True), ('Guambiano', True), ('Guarani', True),
                       ('Guarani (Bolivia)', True), ('Guaraní (Mbyá)', True), ('Guarayu', True),
                       ('Guatemalan Sign Language', True), ('Guayabero', True), ('Guéré', True), ('Guerze', True),
                       ('Guianese Creole', True), ('Gujarati', True), ('Gun', True), ('Guna', True),
                       ('Guyanese Creole English', True), ('Hadiyya', True), ('Haitian Creole', True),
                       ('Hakka (Indonesia)', True), ('Hakka (Taiwan)', True), ('Halia', True),
                       ('Hamshen (Armenian)', True), ('Hamshen (Cyrillic)', True), ('Hano', True), ('Haryanvi', True),
                       ('Hausa', True), ('Havu', True), ('Hawai’i Pidgin', True), ('Hawaiian', True), ('Hawu', True),
                       ('Haya', True), ('Hebrew', True), ('Hehe', True), ('Herero', True), ('Hiligaynon', True),
                       ('Hindi', True), ('Hindi (Fiji)', True), ('Hindi (Roman)', True), ('Hiri Motu', True),
                       ('Hitnu', True), ('Hmong (Green)', True), ('Hmong (White)', True),
                       ('Honduras Sign Language', True), ('Hong Kong Sign Language', True), ('Hopi', True),
                       ('Huastec (San Luis Potosi)', True), ('Huastec (Veracruz)', True),
                       ('Huave (San Mateo del Mar)', True), ('Hula', True), ('Hungarian', True),
                       ('Hungarian Sign Language', True), ('Hunsrik', True), ('Iaai', True), ('Iban', True),
                       ('Ibanag', True), ('Ibinda', True), ('Icelandic', True), ('Idoma', True), ('Igala', True),
                       ('Igbo', True), ('Igede', True), ('Ignaciano', True), ('Ijaw', True), ('Iloko', True),
                       ('Inakeanon', True), ('Indian Sign Language', True), ('Indonesian', True),
                       ('Indonesian Sign Language', True), ('Inga', True), ('Inuktitut (Roman)', True),
                       ('Inuktitut (Syllabics)', True), ('Irish', True), ('Irish Sign Language', True),
                       ('Islander Creole English', True), ('Isoko', True), ('Israeli Sign Language', True),
                       ('Italian', True), ('Italian Sign Language', True), ('Itawit', True), ('Itsekiri', True),
                       ('Iu Mien', True), ('Ivorian Sign Language', True), ('Ixil', True), ('Jamaican Creole', True),
                       ('Jamaican Sign Language', True), ('Japanese', True), ('Japanese Sign Language', True),
                       ('Jarai', True), ('Javanese', True), ('Javanese (Eastern)', True), ('Jejueo', True),
                       ('Jiwaka', True), ('Jula', True), ('Kabardin-Cherkess', True), ('Kabiye', True),
                       ('Kabuverdianu', True), ('Kabyle', True), ('Kachin', True), ('Kadavu', True), ('Kadazan', True),
                       ('Kaingang', True), ('Kaiwá', True), ('Kalanga (Botswana)', True), ('Kalanga (Zimbabwe)', True),
                       ('Kalenjin', True), ('Kalmyk', True), ('Kamayo', True), ('Kamba', True), ('Kambera', True),
                       ('Kamwe', True), ('Kangri (Hamirpuri)', True), ('Kankanaey', True), ('Kannada', True),
                       ('Kanyok', True), ('Karachay-Balkar', True), ('Karakalpak', True),
                       ('Karen (Pwo Northern)', True), ('Karen (Pwo Western)', True), ("Karen (S'gaw)", True),
                       ('Kasem', True), ('Kashubian', True), ('Kazakh', True), ('Kazakh (Arabic)', True), ('Kei', True),
                       ('Kekchi', True), ('Kenyan Sign Language', True), ('Khakass', True), ('Khana', True),
                       ('Khari Boli', True), ('Khasi', True), ('Khmer (Northern)', True), ('Kibala', True),
                       ('Kifuliiru', True), ('Kihemba', True), ('Kikaonde', True), ('Kikongo', True),
                       ('Kikongo ya Leta', True), ('Kikuyu', True), ('Kiluba', True), ('Kimbundu', True),
                       ('Kinande', True), ('Kinaray-a', True), ('Kinyakyusa', True), ('Kinyarwanda', True),
                       ('Kipende', True), ('Kirghiz', True), ('Kiribati', True), ('Kirundi', True), ('Kisi', True),
                       ('Kisii', True), ('Kisonge', True), ('Kituba', True), ('Kokborok', True), ('Kokola', True),
                       ('Komi', True), ('Komi-Permyak', True), ('Kongo', True), ('Konkani (Devanagari)', True),
                       ('Konkani (Kannada)', True), ('Konkani (Roman)', True), ('Kono', True), ('Korean', True),
                       ('Korean (China)', True), ('Korean Sign Language', True), ('Kosraean', True), ('Koti', True),
                       ('Kpelle', True), ('Krio', True), ('Kryashen', True), ('Kuanua', True),
                       ('Kuhane (Subiya)', True), ('Kui', True), ('Kunama', True), ('Kunda', True),
                       ('Kurdish Kurmanji', True), ('Kurdish Kurmanji (Caucasus)', True),
                       ('Kurdish Kurmanji (Cyrillic)', True), ('Kurdish Sorani', True), ('Kurukh', True),
                       ('Kusaal', True), ('Kutchi', True), ('Kuvale (Mucubal)', True), ('Kuy', True),
                       ('Kwangali', True), ('Kwanyama', True), ("Kwara'ae", True), ('Kwasio', True),
                       ('Kyangonde', True), ('Ladin (Gardenese)', True), ('Lahu', True), ('Lakota', True),
                       ('Lamba', True), ('Lambadi', True), ('Lambya', True), ('Lango', True),
                       ('Langue des signes camerounaise', True), ('Laotian', True), ('Lari', True), ('Latgalian', True),
                       ('Latvian', True), ('Latvian Sign Language', True), ('Lauan', True),
                       ('Lebanese Sign Language', True), ('Lega', True), ('Lele', True), ('Lenakel', True),
                       ('Lendu', True), ('Lenje', True), ('Lezgian', True), ('Lhukonzo', True),
                       ('Liberian English', True), ('Limba (West-Central)', True), ('Limbum', True), ('Lingala', True),
                       ('Lisu', True), ('Lithuanian', True), ('Lithuanian Sign Language', True), ('Lokaa', True),
                       ('Lolo', True), ('Loma', True), ('Lomongo', True), ('Lomwe', True), ('Longuda', True),
                       ('Low German', True), ('Luchazi', True), ('Luganda', True), ('Lugbara', True), ('Lunda', True),
                       ('Luo', True), ('Luvale', True), ('Luxembourgish', True), ('Maasai', True), ('Macedonian', True),
                       ('Macua', True), ('Macuata', True), ('Macushi', True), ('Madagascar Sign Language', True),
                       ('Madi', True), ('Madura', True), ('Mafa', True), ('Maguindanao', True),
                       ('Mahorian (Roman)', True), ('Maithili', True), ('Makaa', True), ('Makasae', True),
                       ('Makhuwa-Marrevone', True), ('Makhuwa-Meetto', True), ('Makhuwa-Moniga', True),
                       ('Makhuwa-Shirima', True), ('Makonde', True), ('Malagasy', True), ('Malawi Sign Language', True),
                       ('Malay', True), ('Malay (Papuan)', True), ('Malayalam', True), ('Malayo', True),
                       ('Malaysian Sign Language', True), ('Maltese', True), ('Maltese Sign Language', True),
                       ('Mam', True), ('Mamasa', True), ('Mambae (Ermera)', True), ('Mambwe-Lungu', True),
                       ('Manado Malay', True), ('Mandeali', True), ('Mandinka', True), ('Mandja', True),
                       ('Mandjak', True), ('Mangareva', True), ('Maninkakan (Eastern)', True), ('Manipuri', True),
                       ('Manipuri (Roman)', True), ('Mano', True), ('Mansi', True), ('Manyawa', True), ('Maori', True),
                       ('Mapudungun', True), ('Maquiritari', True), ('Maragoli', True), ('Marathi', True),
                       ('Mari', True), ('Mari (Hill)', True), ('Marquesian (Nuku Hiva)', True), ('Marshallese', True),
                       ('Martiniquan Creole', True), ('Marwari', True), ('Mashi', True), ('Matengo', True),
                       ('Matses', True), ('Mauritian Creole', True), ('Mauritian Sign Language', True), ('Maya', True),
                       ('Maya (Mopán)', True), ('Mayangna', True), ('Mayo', True), ('Mazahua', True),
                       ('Mazatec (Huautla)', True), ('Mbala', True), ('Mbangala', True), ('Mbo', True),
                       ('Mbukushu', True), ('Mbum', True), ('Mbunda', True), ('Medan Hokkien', True), ('Medumba', True),
                       ('Melanesian Sign Language', True), ('Mende', True), ('Mentawai', True), ('Meru', True),
                       ("Meta'", True), ('Mewari', True), ('Mexican Sign Language', True), ('Mi’kmaq', True),
                       ('Min Nan (Quanzhou)', True), ('Min Nan (Taiwan)', True), ('Mingrelian', True),
                       ('Miskito', True), ('Mixe (North Central)', True), ('Mixtec (Costa)', True),
                       ('Mixtec (Guerrero)', True), ('Mixtec (Huajuapan)', True), ('Mixtec (Tilantongo)', True),
                       ('Mixtec (Tlaxiaco)', True), ('Mizo', True), ('Mnong (Central)', True), ('Moba', True),
                       ('Mohawk', True), ('Moksha', True), ('Mongolian', True), ('Mongolian (Traditional)', True),
                       ('Mongolian Sign Language', True), ('Moore', True), ('Motu', True), ('Moundang', True),
                       ('Moussey', True), ('Mozambican Sign Language', True), ('Mundari', True), ('Myanmar', True),
                       ('Myanmar Sign Language', True), ('Nadi', True), ('Nadroga', True), ('Naga (Angami)', True),
                       ('Naga (Liangmai)', True), ('Naga (Rongmei)', True), ('Nagamese', True),
                       ('Nahuatl (Central)', True), ('Nahuatl (Guerrero)', True), ('Nahuatl (Huasteca)', True),
                       ('Nahuatl (Northern Puebla)', True), ('Nahuatl (Veracruz)', True), ('Nama', True),
                       ('Namakura', True), ('Nambya', True), ('Namibian Sign Language', True),
                       ('Namosi-Naitasiri-Serua', True), ('Nancowry', True), ('Navajo', True), ('Ndali', True),
                       ('Ndau', True), ('Ndau (Western)', True), ('Ndebele', True), ('Ndebele (Zimbabwe)', True),
                       ('Ndonga', True), ('Nenets', True), ('Nengone', True), ('Nepali', True),
                       ('Nepali Sign Language', True), ('New Zealand Sign Language', True), ('Newari', True),
                       ('Ngabere', True), ('Ngambaye', True), ('Ngangela', True), ('Ngbaka', True),
                       ('Ngbandi (Northern)', True), ('Ngiemboon', True), ('Ngigua (San Marcos Tlacoyalco)', True),
                       ('Ngombale', True), ('Nhengatu', True), ('Nias', True), ('Nicaraguan Sign Language', True),
                       ('Nicobarese', True), ('Nigerian Pidgin', True), ('Nigerian Sign Language', True),
                       ('Niuean', True), ('Nivaclé', True), ('Njebi', True), ('Nkoya', True),
                       ('Northern Ojibwe (Roman)', True), ('Northern Ojibwe (Syllabics)', True), ('Norwegian', True),
                       ('Norwegian Sign Language', True), ('Nsenga (Mozambique)', True), ('Nsenga (Zambia)', True),
                       ('Nuer', True), ('Nukumanu', True), ('Numèè (Kwenyii)', True), ('Nyaneka', True),
                       ('Nyelâyu', True), ('Nyiha', True), ('Nyungwe', True), ('Nzema', True),
                       ('O’odham (Tohono)', True), ('Obolo', True), ('Odawa', True), ('Odia', True), ('Okpe', True),
                       ('Olunyole', True), ('Ombamba', True), ('Orokaiva', True), ('Oromo', True), ('Ossetian', True),
                       ('Ossetian (Chsan)', True), ('Ossetian (Kudar)', True), ('Otetela', True),
                       ('Otomi (Eastern Highland)', True), ('Otomi (Mezquital Valley)', True),
                       ('Otomi (State of Mexico)', True), ("Pa'o", True), ('Paama', True), ('Páez', True),
                       ('Paicî', True), ('Paiwan', True), ('Palauan', True), ('Palikúr', True), ('Pamona', True),
                       ('Panamanian Sign Language', True), ('Pangasinan', True), ('Papel', True),
                       ('Papiamento (Aruba)', True), ('Papiamento (Curaçao)', True), ('Paraguayan Sign Language', True),
                       ('Pashto', True), ('Pehuenche', True), ('Pemon', True), ('Pennsylvania German', True),
                       ('Persian', True), ('Peruvian Sign Language', True), ('Phimbi', True), ('Phu Thai', True),
                       ('Piaroa', True), ('Pidgin (Cameroon)', True), ('Pidgin (West Africa)', True), ('Pilagá', True),
                       ('Pitjantjatjara', True), ('Pohnpeian', True), ('Polish', True), ('Polish Sign Language', True),
                       ('Pomeranian', True), ('Popoluca (Highland)', True), ("Popti'", True), ("Poqomchi'", True),
                       ('Portuguese (Angola)', True), ('Portuguese (Brazil)', True), ('Portuguese (Mozambique)', True),
                       ('Portuguese (Portugal)', True), ('Portuguese Sign Language', True), ('Pular', True),
                       ('Punjabi', True), ('Punjabi (Shahmukhi)', True), ('Punu', True), ('Puyuma', True),
                       ("Q'anjob'al", True), ('Quebec Sign Language', True), ('Quechua (Ancash)', True),
                       ('Quechua (Ayacucho)', True), ('Quechua (Bolivia)', True), ('Quechua (Cuzco)', True),
                       ('Quechua (Huallaga Huánuco)', True), ('Quechua (Huaylla Wanca)', True),
                       ('Quechua (Lambayeque)', True), ('Quiche', True), ('Quichua (Cañar)', True),
                       ('Quichua (Chibuleo)', True), ('Quichua (Chimborazo)', True), ('Quichua (Cotopaxi)', True),
                       ('Quichua (Imbabura)', True), ('Quichua (Pastaza)', True), ('Quichua (Salasaca)', True),
                       ('Quichua (Santiago del Estero)', True), ('Quichua (Tena)', True), ('Ra', True),
                       ('Rapa Nui', True), ('Rarotongan', True), ('Réunion Creole', True), ('Romanian', True),
                       ('Romanian (Vlach, Bačka)', True), ('Romanian (Vlach)', True), ('Romanian Sign Language', True),
                       ('Romansh (Ladin)', True), ('Romansh (Sursilvan)', True), ('Romany (Albania)', True),
                       ('Romany (Argentina)', True), ('Romany (Arli)', True), ('Romany (Bosnia and Herzegovina)', True),
                       ('Romany (Chile)', True), ('Romany (Crimea)', True), ('Romany (Eastern Slovakia)', True),
                       ('Romany (France)', True), ('Romany (Germany)', True), ('Romany (Kalderash, Russia)', True),
                       ('Romany (Lovari, Chokeshi)', True), ('Romany (Lovari, Hungary)', True),
                       ('Romany (Macedonia)', True), ('Romany (Macedonia) Cyrillic', True), ('Romany (Meçkar)', True),
                       ('Romany (Moldova) Cyrillic', True), ('Romany (Northern Greece)', True),
                       ('Romany (Northern Russia)', True), ('Romany (Poland)', True), ('Romany (Romania)', True),
                       ('Romany (Serbia)', True), ('Romany (Southern Greece)', True), ('Romany (Ukraine)', True),
                       ('Romany (Vlax, Russia)', True), ('Romany (Western Bulgaria)', True), ('Ronga', True),
                       ('Rotuman', True), ('Roviana', True), ('Rukai', True), ('Rumanyo', True), ('Rungus', True),
                       ('Runyankore', True), ('Russian', True), ('Russian Sign Language', True),
                       ('Rusyn (Carpathian)', True), ('Rutoro', True), ('Rwandan Sign Language', True),
                       ('Saami (North)', True), ('Sadri (Devanagari)', True), ('Saint Lucian Creole', True),
                       ('Saluan', True), ('Salvadoran Sign Language', True), ('Samburu', True), ('Samia', True),
                       ('Samoan', True), ('Samoan Sign Language', True), ('Sanga', True), ('Sangir', True),
                       ('Sango', True), ('Santhali (Devanagari)', True), ('Santhali (Roman)', True),
                       ('Sãotomense', True), ('Sar', True), ('Saramaccan', True), ('Sarnami', True), ('Sasak', True),
                       ('Sateré-Mawé', True), ('Scottish Gaelic', True), ('Seediq', True), ('Sehwi', True),
                       ('Sena', True), ('Senoufo (Cebaara)', True), ('Sepedi', True), ('Sepulana', True),
                       ('Serbian (Cyrillic)', True), ('Serbian (Roman)', True), ('Serbian Sign Language', True),
                       ('Serer', True), ('Sesotho (Lesotho)', True), ('Sesotho (South Africa)', True),
                       ('Setswana', True), ('Seychelles Creole', True), ('Shan', True), ('Shawi', True),
                       ('Shilluk', True), ('Shipibo-Conibo', True), ('Shona', True), ('Shuar', True), ('Shughni', True),
                       ('Sidama', True), ('Silesian', True), ('Silozi', True), ('Sindhi (Devanagari)', True),
                       ('Sindhi (Indonesia)', True), ('Singapore Sign Language', True), ('Sinhala', True),
                       ('Slovak', True), ('Slovak Sign Language', True), ('Slovenian', True),
                       ('Slovenian Sign Language', True), ('Soli', True), ('Solomon Islands Pidgin', True),
                       ('Somali', True), ('Songo', True), ('Songomeno', True), ('Soninke', True),
                       ('South African Sign Language', True), ('Spanish', True), ('Spanish (Spain)', True),
                       ('Spanish Sign Language', True), ('Sranantongo', True), ('Sri Lankan Sign Language', True),
                       ('Sukuma', True), ('Sunda', True), ('Sundargadi', True), ('Surigaonon', True),
                       ('Suriname Sign Language', True), ('Susu', True), ('Svan (Lower)', True), ('Svan (Upper)', True),
                       ('Swahili', True), ('Swahili (Congo)', True), ('Swahili (Katanga)', True), ('Swati', True),
                       ('Swazi Sign Language', True), ('Swedish', True), ('Swedish Sign Language', True),
                       ('Swiss German', True), ('Swiss German Sign Language', True), ('Sylheti (Bengali)', True),
                       ('Taabwa', True), ('Tabasaran', True), ('Tagalog', True), ('Tahitian', True), ('Tairuma', True),
                       ('Taita', True), ('Taiwanese Sign Language', True), ('Tajiki', True),
                       ('Tajiki (Samarkand)', True), ('Talian', True), ('Talysh', True), ('Tamang (Eastern)', True),
                       ('Tamang (Western)', True), ('Tamil', True), ('Tamil (Roman)', True), ('Tandroy', True),
                       ('Tangkhul', True), ('Tankarana', True), ('Tanzanian Sign Language', True),
                       ('Tarahumara (Central)', True), ('Tarahumara (Western)', True), ('Tarascan', True),
                       ('Tarok', True), ('Taroko', True), ('Tatar', True), ('Tausug', True), ('Telugu', True),
                       ('Tem', True), ('Teochew', True), ('Teochew (Indonesia)', True), ('Terêna', True),
                       ('Tetun Belu', True), ('Tetun Dili', True), ('Tewe', True), ('Thai', True),
                       ('Thai (Korat)', True), ('Thai (Northeastern)', True), ('Thai (Northern)', True),
                       ('Thai (Southern)', True), ('Thai Sign Language', True), ('Thai Song', True), ('Themne', True),
                       ('Tibetan', True), ('Ticuna', True), ('Tigrinya', True), ('Tii', True), ('Tiv', True),
                       ('Tlapanec', True), ("To'abaita", True), ('Toaripi', True), ('Toba', True), ('Tojolabal', True),
                       ('Tok Pisin', True), ('Tokelauan', True), ('Tongan', True), ('Toraja', True),
                       ('Torres Strait Creole', True), ('Totonac', True), ('Toupouri', True),
                       ('Trinidad and Tobago Sign Language', True), ('Trinidadian Creole', True), ('Tshiluba', True),
                       ('Tshwa', True), ('Tsimané', True), ('Tsonga', True), ('Tucano', True), ('Tulu', True),
                       ('Tunen', True), ('Turkana', True), ('Turkish', True), ('Turkish (Meskhetian)', True),
                       ('Turkish Sign Language', True), ('Turkmen', True), ('Turkmen (Cyrillic)', True),
                       ('Tuvaluan', True), ('Tuvinian', True), ('Twi', True), ('Tyrewuju', True), ('Tzeltal', True),
                       ('Tzotzil', True), ('Tzutujil', True), ('Uab Meto', True), ('Udmurt', True),
                       ('Ugandan Sign Language', True), ('Uighur (Arabic)', True), ('Uighur (Cyrillic)', True),
                       ('Ukrainian', True), ('Umbundu', True), ('Urdu', True), ('Urhobo', True), ('Uripiv', True),
                       ('Uruguayan Sign Language', True), ('Uruund', True), ('Uzbek', True), ('Uzbek (Horezm)', True),
                       ('Uzbek (Roman)', True), ('Valencian', True), ('Venda', True),
                       ('Venezuelan Sign Language', True), ('Vezo', True), ('Vietnamese', True),
                       ('Vietnamese Sign Language', True), ('Wa', True), ('Waama', True), ('Wallisian', True),
                       ('Wapishana', True), ('Warao', True), ('Waray-Waray', True), ('Wayuunaiki', True),
                       ('Wejewa', True), ('Welsh', True), ('Wichi', True), ('Wixárika', True), ('Wolaita', True),
                       ('Wolof', True), ('Xârâcùù', True), ('Xavante', True), ('Xhosa', True), ('Yacouba', True),
                       ('Yakoma', True), ('Yakutsk', True), ('Yambassa', True), ('Yami', True), ('Yansi', True),
                       ('Yapese', True), ('Yaqui', True), ('Yemba', True), ('Yombe', True), ('Yong', True),
                       ('Yoruba', True), ('Yuanga', True), ('Yukpa', True), ('Zambian Sign Language', True),
                       ('Zande', True), ('Zapotec (del Valle)', True), ('Zapotec (Guevea)', True),
                       ('Zapotec (Isthmus)', True), ('Zapotec (Ixtlán)', True), ('Zapotec (Lachiguiri)', True),
                       ('Zapotec (Loxicha)', True), ('Zapotec (Quiatoni)', True), ('Zapotec (Quiavicuzas)', True),
                       ('Zapotec (Santiago Xanica)', True), ('Zapotec (Villa Alta)', True), ('Zarma', True),
                       ('Zimbabwe Sign Language', True), ('Zulu', True), ('中文（海南话）', True)]
